config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users
  resources :products
  resources :reviews
  resources :categorys 
  resources :product_categorys
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :product_categorys
    has_many :products, through: :product_categorys
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :reviews
    has_one :product_category
    has_one :category, through: :product_category


       
   
 
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
    belongs_to :product
    belongs_to :category
    
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :product

    validates :rating, presence: true
    validates :title, presence: true
    validates :post, presence: true

    def self.featured_review
        @featured = []
        
        Review.all.each do |review|
            if review.rating == 10
            @featured << review.product.name
            else
            end
        end 

    @featured.uniq
       
        
       end
   


end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :products, through: :reviews

    validates :name, presence: true
    validates :birthday, presence: true
    validates :location, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categorys_controller.rb
class CategorysController < ApplicationController

    def index
        @categorys = Category.all 
    end

    def show
        @category = Category.find(params[:id])
    end
end

app/controllers/product_categorys_controller.rb
class ProductCategorysController < ApplicationController

    def index
        @prodcats = ProductCategory.all 
    end

    def new
        @prodcat = ProductCategory.new
    end

    def create 
        @prodcat= ProductCategory.create(product_category_params)
        redirect_to @prodcat
    end

    def product_category_params
        params.require(:product_category).permit(:product_id, :user_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def index
        @products = Product.all 
        @home_page = true
    end

    def show
        @product = Product.find(params[:id])
    end

    def new
        @product = Product.new
    end

    def create 
        @product= Product.create(product_params)
       
    end

    def destroy 
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to products_path
    end

    def product_params
        params.require(:product).permit(:name, :brand, :price, :cat_id)
    end

   
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def index
        @reviews = Review.all 
    end

    def show
        @review = Review.find(params[:id])
    end

    def new
        @review = Review.new
    end

    def create 
        @review = Review.new(review_params)
        
        if @review.valid?
            @review.save
            Review.create(review_params)
            redirect_to @review
        else 
            render :new  
        end
    end

    def destroy 
        @review = Review.find(params[:id])
        @review.destroy
        redirect_to reviews_path
    end

    def review_params
        params.require(:review).permit(:user_id, :product_id, :rating, :title, :post)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all 
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create 
        @user = User.new(user_params)
        
        if @user.valid?
            @user.save
            User.create(user_params)
            redirect_to @user
        else 
            render :new  
        end
    end

    def destroy 
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path
    end

    def user_params
        params.require(:user).permit(:name, :birthday, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categorys/index.html.erb
<h1 style="color:Fuchsia;"><font face="Copperplate"><font size="+5">Categories</font></h1>
<hr><br>
<font face="Copperplate"><font size="+1">
<% @categorys.each do |category| %>
    <%= link_to category.name, category_path(category) %><br><br>
<% end %>
</font><br>

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQv9ll45y3erYdB4Rzi6qauTR_3dMMvbs1eXQ&usqp=CAU" alt="Smiley face" width="400" height="300" style="vertical-align:middle;margin:50px 0px">

app/views/categorys/show.html.erb
<h1 style="color:Fuchsia;"><font face="Copperplate"><font size="+5"><%= @category.name %> Products</font></h1>
<hr><br>

<font face="Copperplate"><font size="+1">
<% @category.products.each do |product| %>
    <%= link_to product.name, product_path(product) %><br><br>
<% end %>
</font><br>


<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQv9ll45y3erYdB4Rzi6qauTR_3dMMvbs1eXQ&usqp=CAU" alt="Smiley face" width="400" height="300" style="vertical-align:middle;margin:50px 0px">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
   
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<body class="<%= @home_page ? 'homepage' : 'background-color: #000'%>">

<h1 style="color:Black;"><font face="Copperplate"><font size="+2">Products</font></h1>
<br>
<font face="Copperplate">
<% @products.each do |product| %>
    <%= link_to product.name, product %><br><br>
<% end %>
</font><br>



<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3OLhYrOibgeS0tjAu9rWOkR17lpL8MbR-rg&usqp=CAU" alt="Smiley face" width="400" height="300" style="vertical-align:middle;margin:50px 0px">

app/views/products/show.html.erb
<h1 style="color:Black;"><font face="Copperplate"><font size="+5">Product</font></h1>
<br>


<font face="Copperplate"><font size="+1">
Name: <%= @product.name %><br><br>
Brand: <%= @product.brand %><br><br>
Price: <%= @product.price%><br><br>
Category: <%= link_to @product.category.name, category_path(@product.category.id)%><br><br>
Reviews: <% @product.reviews.each do |review| %><br>
    <%=link_to review.title, review %><br>
    <%end %><br><br>
<%= button_to "Delete Product", @product, method: :delete %><br><br>
</font><br>

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8hVRk4F070rZWuMX23lgrBz43w0RvuVfjFA&usqp=CAU" alt="Smiley face" width="400" height="300" style="vertical-align:middle;margin:50px 0px">

app/views/reviews/index.html.erb
<h1 style="color:Black;"><font face="Copperplate"><font size="+5">Reviews</font></h1>
<br>

<font face="Copperplate">
<% @reviews.each do |review| %>
    <%= link_to review.product.name, review %><br><br>
<% end %>

<h1><font face="Copperplate"> Highest Ratings: </font></h1>
<% @reviews.featured_review.each do |review| %>
<%= link_to review %><br><br>
<% end %>
</font><br>
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsZFtdrlfxZKaYih2cofkTTTX8TSjBaUJqyg&usqp=CAU" class="img-fluid" alt="...">

app/views/reviews/new.html.erb
<h1 style="color:Black;"><font face="Copperplate"><font size="+5">Create A Review!</font></h1>
<br>
<font face="Copperplate">

<%= form_for @review do |f| %>
    User: <%= f.collection_select :user_id, User.all, :id, :name %><br><br>
    Product: <%= f.collection_select :product_id, Product.all, :id, :name %><br><br>
    Rating: <%= f.text_field :rating%><br><br>
    Title: <%=f.text_field :title%><br><br>
    Post: <%=f.text_area :post%> <br><br>
    <%= f.submit %>
    <% end %>

    </font><br>

    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsZFtdrlfxZKaYih2cofkTTTX8TSjBaUJqyg&usqp=CAU" class="img-fluid" alt="...">

app/views/reviews/show.html.erb
<h1 style="color:Black;"><font face="Copperplate"><font size="+5">Review</font></h1>
<br>

<font face="Copperplate">
<h2 style="color:Fuchsia;"><b>User: <%= link_to @review.user.name, user_path(@review.user)%></b><br><br></h2>
Product Brand: <%= link_to @review.product.brand, product_path(@review.product)%><br><br>
Product Name: <%= link_to @review.product.name, product_path(@review.product)%><br><br>
Rating: <%= @review.rating %><br><br>
Title: <%= @review.title %><br><br>
Post: <%= @review.post %><br><br>
<%= button_to "Delete Review", @review, method: :delete %><br><br>
</font><br>

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsZFtdrlfxZKaYih2cofkTTTX8TSjBaUJqyg&usqp=CAU" class="img-fluid" alt="...">

app/views/users/index.html.erb
<h1 style="color:Black;"><font face="Copperplate"><font size="+5">Users</font></h1>
<br>

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPvenS768GXtv_q80QoyEXl0_bU08Wp0EuyQ&usqp=CAU" alt="Smiley face" width="250" height="250" style="vertical-align:middle;margin:50px 0px"><br>

<font face="Copperplate"><font size="+1">
<% @users.each do |user| %>
    <%= link_to user.name, user %><br><br>
<% end %>
</font><br>

app/views/users/new.html.erb
<h1 style="color:Black;"><font face="Copperplate"><font size="+5">Create User</font></h1>
<br>
<font face="Copperplate">
<%= form_for @user do |f| %>
    Name: <%= f.text_field :name%><br><br>
    Birthday: <%=f.text_field :birthday%><br><br>
    Location: <%=f.text_field :location%> <br><br>
    <%= f.submit %>
    </font>
    <% end %><br>

    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsZFtdrlfxZKaYih2cofkTTTX8TSjBaUJqyg&usqp=CAU" class="img-fluid" alt="...">

app/views/users/show.html.erb
<h1 style="color:Black;"><font face="Copperplate"><font size="+5">User</font></h1>
<br>
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_VV06q1harHhWwY29fxZTDy4L0aD7tsn_xA&usqp=CAU" alt="Smiley face" width="200" height="200" style="vertical-align:middle;margin:50px 0px"><br>

<font face="Copperplate">
Name: <%= @user.name %><br><br>
Birthday: <%= @user.birthday %><br><br>
Location: <%= @user.location %><br><br>
Reviews: <% @user.reviews.each do |review| %><br><br>
    <%=link_to review.title, review %><br><br>
    <%end %><br><br>
<%= button_to "Delete User", @review, method: :delete %><br><br>
</font><br>